sbatch 01_batch_gaussianProcessRegression-0.sh
sleep 1
sbatch 01_batch_gaussianProcessRegression-1.sh
sleep 1
sbatch 01_batch_gaussianProcessRegression-2.sh
sleep 1
sbatch 01_batch_gaussianProcessRegression-3.sh
sleep 1
sbatch 01_batch_gaussianProcessRegression-4.sh
sleep 1
sbatch 01_batch_gaussianProcessRegression-5.sh
sleep 1
sbatch 01_batch_gaussianProcessRegression-6.sh
sleep 1
sbatch 01_batch_gaussianProcessRegression-7.sh
sleep 1
sbatch 01_batch_gaussianProcessRegression-8.sh
sleep 1
sbatch 01_batch_gaussianProcessRegression-9.sh
